---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "33.33.33.110", adapter: 2}]

provisioner:
  name: chef_solo
  environments_path: environments
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"

platforms:
  - name: centos-6
    driver_plugin: vagrant
    driver_config:
      box: centos-6-20140121
      box_url: http://vagrant.osuosl.org/centos-6-20140121.box

  - name: ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: ubuntu-12.04-20140121
      box_url: http://vagrant.osuosl.org/ubuntu-12.04-20140121.box
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: vagrant
    run_list:
      - recipe[ganeti_webmgr::default]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
    attributes:
      ganeti_webmgr:
        database:
          engine: django.db.backends.sqlite3
          name: /home/vagrant/gwm.db

  - name: mysql
    provisioner:
      solo_rb:
        environment: vagrant
    run_list:
      - recipe[ganeti_webmgr::mysql]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
